WINDOW_TITLE = "Timeseries Visualisation Software"
WINDOW_SIZE = "400x400"
FILE_PATH = '/Users/isacfiorotti/Documents/COMP4031 - Personal Project/timeseries-visualisation-software/src/app/data/data.csv'
CHUNK_SIZE = 25000
MP_WINDOW_SIZE = 120
MP_THRESHOLD = 2
GAP_THRESHOLD = 0.01
BASE_SIGNAL_LENGTH = 220
CLUSTER_THRESHOLD = 14
